### ISSUE TITLE
Mouse issues on Win10

### ISSUE THREAD

**Issue by zenitsuy** [Kirillathome/FNAK-Feedback#1]
There is a bug on the objectively best operating system of all time Microsoft Windows, courtesy of our great corporate overlord Mr. Bill Gates, where your mouse might randomly dissapear when in fullscreen and switching between multiple windows.
Best regards,
a Windows User who hates his life for using Windows 10 next to Arch btw (not gay btw)

**Comment by Kirillathome** [comment]
I think I simply forgot to add some code lol

**Comment by Kirillathome** [comment]
Added the code so that it _shouldn't_ happen
